[package]
name = "rusty-rays"
version = "0.1.0"
authors = ["Phillip Raffns√∏e <phillip@praffn.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
assert_approx_eq = "1.1.0"
